---

- name: Restart specific Docker containers
  hosts: all
  become: true
  vars:
    container_name: ""
  
  tasks:
    - name: Restart matching containers
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: started
        restart: yes
      when: container_name != ""

    - name: Get container info
      community.docker.docker_container_info:
        name: "{{container_name}}"
      register: container_info
      when: container_name != ""

    - name: Log container info
      debug:
        msg: "{{container_info}}"
      when: container_name != "" and container_info != ""
