
configs:
  nginx_conf:
    file: ./nginx.conf

secrets:
  nginx_cert_pem:
    file: /home/certificate.pem
  nginx_cert_key:
    file: /home/certificate.key
  db_password:
    file: /home/docker/secrets/db_password.txt
  db_root_password: 
    file: /home/docker/secrets/db_root_password.txt

volumes:
  portainer:
    name: portainer
    driver_opts:
      o: bind
      device: /home/data/portainer/
      type: none
  db:
    name: db 
    driver_opts:
      o: bind
      device: /home/data/db/
      type: none

networks:
  internal_network:

services:
  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    working_dir: /etc/nginx/
    restart: always
    ports:
      - 443:443
      - 80:80
      - 9090:9090
      - 8080:8080
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: nginx_cert_pem
        target: /etc/nginx/certs/certificate.pem
      - source: nginx_cert_key
        target: /etc/nginx/certs/certificate.key
    networks:
      - internal_network

  wordpress:
    container_name: wordpress
    image: wordpress:6.7.1-php8.1-apache
    restart: always
    networks:
      - internal_network
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: najib
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - db_password

  db:
    image: mysql:8.0-debian
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: najib
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    networks:
      - internal_network
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    networks:
      - internal_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9091:9090
    restart: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal_network
