
# Demo servers compose

services:
  server:
    # image: alpine_server:local
    profiles: ["alpine"]
    hostname: alpine
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add openssh sudo python3
        RUN ssh-keygen -A
        RUN adduser -D najib
        RUN echo 'najib ALL=(ALL) ALL' >> /etc/sudoers
        RUN echo 'najib:1111' | chpasswd
    privileged: true
    entrypoint: /usr/sbin/sshd -D
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any

    ports:
      - "4040-4042:22"
    networks:
      - internalNet

  debian-server:
    profiles: ["debian"]
    build:
      dockerfile_inline: |
        FROM debian:latest
        RUN apt-get update
        RUN apt-get install -y openssh-server sudo python3
        RUN mkdir /run/sshd
        RUN ssh-keygen -A
        RUN useradd -m najib
        RUN echo 'najib:1111' | chpasswd
        RUN echo 'najib ALL=(ALL) ALL' >> /etc/sudoers
    # image: debian_server:local
    hostname: debian
    privileged: true
    entrypoint: /usr/sbin/sshd -D
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - "4043-4045:22"
    networks:
      - internalNet

networks:
  internalNet:
