---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    key_name: my_aws
    ec2_user: admin
    region: us-east-1
    image: ami-0779caf41f9ba54f0
    instance_type: t2.micro
    subnet_id: subnet-0f2eedcdf94ab23eb
    sec_group: ansible-sg
    vpc_id: vpc-0842ccdf1a5425841
    key_path: ~/.ssh/my_aws

  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Security group for Ansible"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        rules:
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
            rule_desc: "SSH access"
          - proto: tcp
            ports: [80]
            cidr_ip: 0.0.0.0/0
            rule_desc: "HTTP access"
          - proto: tcp
            ports: [443]
            cidr_ip: 0.0.0.0/0
            rule_desc: "HTTPS access"
        tags:
          Name: "{{ sec_group }}"
          Environment: "ansible-test"
      register: security_group

    - name: Check if key pair already exists
      amazon.aws.ec2_key_info:
        names: ["{{ key_name }}"]
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      register: key_pair_info

    - name: Create key pair (upload existing public key)
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        key_material: "{{ lookup('file', '~/.ssh/my_aws.pub') }}"
        state: present
      when: key_pair_info.keypairs | length == 0

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "ansible-instance"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ instance_type }}"
        security_groups: ["{{ sec_group }}"]
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        image_id: "{{ image }}"
        network:
          assign_public_ip: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: "ansible-instance"
          Environment: "ansible-test"
        state: running
      register: ec2

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      delegate_to: localhost

    - name: Save instance info to inventory file
      copy:
        dest: ../inventory.yml
        content: |
          all:
            hosts:
              ec2_instance:
                ansible_host: "{{ ec2.instances[0].public_ip_address }}"
                ansible_user: "{{ ec2_user }}"
                ansible_ssh_private_key_file: "{{ key_path }}"
      delegate_to: localhost

    - name: Display instance information
      debug:
        msg:
          - "Instance created successfully!"
          - "Instance ID: {{ ec2.instances[0].instance_id }}"
          - "Public IP: {{ ec2.instances[0].public_ip_address }}"
          - "SSH Command: ssh -i ~/.ssh/my_aws {{ ec2_user }}@{{ ec2.instances[0].public_ip_address }}"
